DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  first_name TEXT,
  last_name TEXT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT "student"
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE quiz_score (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  taker_id INTEGER NOT NULL,
  date_taken TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  quiz_taken TEXT NOT NULL,
  score REAL NOT NULL DEFAULT 0,
  FOREIGN KEY (taker_id) REFERENCES user (id)
);